---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/lines/{lineId}":
    get:
      summary: Get line content from file
      tags:
      - Lines
      parameters:
      - name: lineId
        in: path
        description: Line number
        required: true
        format: int64
        schema:
          type: integer
      responses:
        '200':
          description: Found Line
          content: {}
        '400':
          description: Must be an integer
          content: {}
        '413':
          description: Number line is to big
          content: {}
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
